# Generated by Django 6.0.7 on 2026-07-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('MPESA', 'M-Pesa'), ('CARD', 'Card'), ('CASH', 'Cash')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
